// Normalize sword sprites for nexus-survival.
//  1. 2x nearest-neighbor upscale of 5 inventory icons (16x16 frames -> 32x32)
//  2. Update their JSON metadata (width/height: 16 -> 32, offsets x2 if any)
//  3. Round-trip 6 "color family" world sprites + their item versions through
//     tile-studio's quantize for visual comparison (writes to a review folder).
//  4. Replace sword.png (14x14 stub) with a new 32x32 character sheet (5x9 grid)
//     and an item-sword.png inventory strip (6x1 of 32x32) via paint primitives.
//
// Source of truth: packages/shared/assets/.
// Downstream: packages/bq-wiki/public/ is repopulated by copy-assets.mjs.
// We write to BOTH shared/assets and public/ so the dev preview shows changes
// without re-running the copy step; out/ is regenerated by `next build`.

import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { PNG } from '/sessions/dreamy-cool-pascal/mnt/tile-studio/mcp-server/node_modules/pngjs/lib/png.js';

const ROOT = '/sessions/dreamy-cool-pascal/mnt/nexus-survival';
const SRC_IMG = `${ROOT}/packages/shared/assets/img`;
const SRC_SPR = `${ROOT}/packages/shared/assets/sprites`;
const PUB_IMG = `${ROOT}/packages/bq-wiki/public/img`;
const PUB_SPR = `${ROOT}/packages/bq-wiki/public/sprites`;
const REVIEW = `${ROOT}/assets/_sword-review`;

async function readPNG(p) {
  const buf = await fs.readFile(p);
  return PNG.sync.read(buf);
}
async function writePNG(p, png) {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, PNG.sync.write(png, { colorType: 6 }));
}
async function writeBoth(name, png) {
  await writePNG(`${SRC_IMG}/${name}`, png);
  await writePNG(`${PUB_IMG}/${name}`, png);
}
function upscale2xNearest(src) {
  const { width, height, data } = src;
  const W = width * 2, H = height * 2;
  const out = new PNG({ width: W, height: H });
  out.data = Buffer.alloc(W * H * 4);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const o = (y * width + x) * 4;
      const r = data[o], g = data[o + 1], b = data[o + 2], a = data[o + 3];
      for (let dy = 0; dy < 2; dy++) for (let dx = 0; dx < 2; dx++) {
        const d = ((y * 2 + dy) * W + (x * 2 + dx)) * 4;
        out.data[d] = r; out.data[d + 1] = g; out.data[d + 2] = b; out.data[d + 3] = a;
      }
    }
  }
  return out;
}

// ---------- Phase 1: upscale 5 inventory icons ----------
const upscaleTargets = [
  'item-bluesword.png',
  'item-goldensword.png',
  'item-redsword.png',
  'item-sword1.png',
  'item-sword2.png',
];
console.log('# Phase 1: upscale inventory icons 16x16 -> 32x32 frames\n');
for (const name of upscaleTargets) {
  const before = await readPNG(`${SRC_IMG}/${name}`);
  if (before.width !== 96 || before.height !== 16) {
    console.log(`  SKIP ${name}: expected 96x16, got ${before.width}x${before.height}`);
    continue;
  }
  const after = upscale2xNearest(before);
  await writeBoth(name, after);
  console.log(`  ${name}: 96x16 -> ${after.width}x${after.height}`);
}

// ---------- Phase 1b: update JSON metadata ----------
console.log('\n# Phase 1b: update JSON metadata (width/height 16 -> 32)\n');
const jsonTargets = upscaleTargets.map((n) => n.replace(/\.png$/, '.json'));
for (const name of jsonTargets) {
  for (const dir of [SRC_SPR, PUB_SPR]) {
    const p = `${dir}/${name}`;
    try {
      const meta = JSON.parse(await fs.readFile(p, 'utf-8'));
      if (meta.width !== 16 || meta.height !== 16) continue;
      meta.width = 32; meta.height = 32;
      if (typeof meta.offset_x === 'number' && meta.offset_x !== 0) meta.offset_x *= 2;
      if (typeof meta.offset_y === 'number' && meta.offset_y !== 0) meta.offset_y *= 2;
      await fs.writeFile(p, JSON.stringify(meta, null, 2));
      console.log(`  ${dir.endsWith('public/sprites') ? 'public' : 'shared'}/${name}: updated to 32x32`);
    } catch (e) {
      if (e.code !== 'ENOENT') console.log(`  ERR ${p}: ${e.message}`);
    }
  }
}

// ---------- Phase 2: quantize round-trip review ----------
console.log('\n# Phase 2: quantize round-trip (review only, originals unchanged)\n');
const colorFamily = ['bluesword.png', 'redsword.png', 'goldensword.png', 'flamingsword.png', 'sword1.png', 'sword2.png'];
const itemColorFamily = upscaleTargets.concat(['item-flamingsword.png']);
const reviewTargets = [...colorFamily, ...itemColorFamily];
await fs.mkdir(REVIEW, { recursive: true });

function quantizeSimple(src, maxColors) {
  const { width: w, height: h, data } = src;
  const counts = new Map();
  const pixelKey = new Uint32Array(w * h);
  for (let i = 0, p = 0; i < data.length; i += 4, p++) {
    const a = data[i + 3];
    if (a < 1) { pixelKey[p] = 0; continue; }
    const key = ((data[i] << 16) | (data[i + 1] << 8) | data[i + 2]) >>> 0;
    pixelKey[p] = key | 0x1000000;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  let entries = [...counts.entries()].map(([rgb, n]) => ({
    r: (rgb >> 16) & 0xff, g: (rgb >> 8) & 0xff, b: rgb & 0xff, n,
  }));
  while (entries.length > maxColors) {
    let bI = 0, bJ = 1, bD = Infinity;
    for (let i = 0; i < entries.length; i++) {
      for (let j = i + 1; j < entries.length; j++) {
        const A = entries[i], B = entries[j];
        const dr = A.r - B.r, dg = A.g - B.g, db = A.b - B.b;
        const d = dr * dr + dg * dg + db * db;
        if (d < bD) { bD = d; bI = i; bJ = j; }
      }
    }
    const A = entries[bI], B = entries[bJ];
    const t = A.n + B.n;
    entries[bI] = { r: Math.round((A.r * A.n + B.r * B.n) / t), g: Math.round((A.g * A.n + B.g * B.n) / t), b: Math.round((A.b * A.n + B.b * B.n) / t), n: t };
    entries.splice(bJ, 1);
  }
  const out = new PNG({ width: w, height: h });
  out.data = Buffer.alloc(w * h * 4);
  for (let p = 0; p < pixelKey.length; p++) {
    if ((pixelKey[p] & 0x1000000) === 0) { out.data[p * 4 + 3] = 0; continue; }
    const key = pixelKey[p] & 0xffffff;
    const sr = (key >> 16) & 0xff, sg = (key >> 8) & 0xff, sb = key & 0xff;
    let bi = 0, bd = Infinity;
    for (let i = 0; i < entries.length; i++) {
      const e = entries[i];
      const dr = sr - e.r, dg = sg - e.g, db = sb - e.b;
      const d = dr * dr + dg * dg + db * db;
      if (d < bd) { bd = d; bi = i; }
    }
    const e = entries[bi];
    out.data[p * 4] = e.r; out.data[p * 4 + 1] = e.g; out.data[p * 4 + 2] = e.b; out.data[p * 4 + 3] = 255;
  }
  return { png: out, paletteSize: entries.length };
}

for (const name of reviewTargets) {
  try {
    const src = await readPNG(`${SRC_IMG}/${name}`);
    for (const budget of [8, 16]) {
      const r = quantizeSimple(src, budget);
      await writePNG(`${REVIEW}/${name.replace(/\.png$/, `_q${budget}.png`)}`, r.png);
    }
    console.log(`  ${name}: quantized at 8 + 16 colors`);
  } catch (e) {
    if (e.code === 'ENOENT') console.log(`  SKIP ${name}: not found`);
    else console.log(`  ERR ${name}: ${e.message}`);
  }
}

// ---------- Phase 3: replace sword.png with new 32x32 character sheet ----------
console.log('\n# Phase 3: regenerate sword.png + item-sword.png (programmatic)\n');
const SHEET_W = 160, SHEET_H = 288, FRAME = 32;
function newSheet(w, h) {
  const png = new PNG({ width: w, height: h });
  png.data = Buffer.alloc(w * h * 4);
  return png;
}
function px(p, x, y, r, g, b, a = 255) {
  if (x < 0 || y < 0 || x >= p.width || y >= p.height) return;
  const o = (y * p.width + x) * 4;
  p.data[o] = r; p.data[o + 1] = g; p.data[o + 2] = b; p.data[o + 3] = a;
}
function rect(p, x, y, w, h, r, g, b, a = 255) {
  for (let dy = 0; dy < h; dy++) for (let dx = 0; dx < w; dx++) px(p, x + dx, y + dy, r, g, b, a);
}
function line(p, x0, y0, x1, y1, r, g, b, a = 255) {
  const dx = Math.abs(x1 - x0), dy = -Math.abs(y1 - y0);
  const sx = x0 < x1 ? 1 : -1, sy = y0 < y1 ? 1 : -1;
  let err = dx + dy, x = x0, y = y0;
  while (true) {
    px(p, x, y, r, g, b, a);
    if (x === x1 && y === y1) break;
    const e2 = 2 * err;
    if (e2 >= dy) { err += dy; x += sx; }
    if (e2 <= dx) { err += dx; y += sy; }
  }
}

// Iron sword palette: 6 colors, on/off alpha (matches MU 5-7 color discipline).
const STEEL_DARK = [70, 78, 92], STEEL = [128, 138, 156], STEEL_HI = [192, 200, 220];
const GRIP = [80, 50, 30], GUARD = [180, 150, 90], POMMEL = [180, 150, 90];

function drawSword(png, cx, cy, orient, bob = 0) {
  const ox = cx + 16, oy = cy + 16;
  if (orient === 'right') {
    const yC = oy + bob;
    rect(png, ox - 8, yC - 1, 4, 3, ...GRIP);
    rect(png, ox - 9, yC, 1, 1, ...POMMEL);
    rect(png, ox - 4, yC - 3, 1, 7, ...GUARD);
    rect(png, ox - 3, yC - 1, 12, 3, ...STEEL);
    line(png, ox - 3, yC - 1, ox + 8, yC - 1, ...STEEL_HI);
    px(png, ox + 9, yC, ...STEEL);
    line(png, ox - 3, yC + 1, ox + 8, yC + 1, ...STEEL_DARK);
  } else if (orient === 'up') {
    const xC = ox + bob;
    rect(png, xC - 1, oy + 4, 3, 4, ...GRIP);
    rect(png, xC, oy + 8, 1, 1, ...POMMEL);
    rect(png, xC - 3, oy + 3, 7, 1, ...GUARD);
    rect(png, xC - 1, oy - 9, 3, 12, ...STEEL);
    line(png, xC - 1, oy - 9, xC - 1, oy + 2, ...STEEL_HI);
    px(png, xC, oy - 10, ...STEEL);
    line(png, xC + 1, oy - 9, xC + 1, oy + 2, ...STEEL_DARK);
  } else {
    const xC = ox + bob;
    rect(png, xC - 1, oy - 8, 3, 4, ...GRIP);
    rect(png, xC, oy - 9, 1, 1, ...POMMEL);
    rect(png, xC - 3, oy - 4, 7, 1, ...GUARD);
    rect(png, xC - 1, oy - 3, 3, 12, ...STEEL);
    line(png, xC - 1, oy - 3, xC - 1, oy + 8, ...STEEL_HI);
    px(png, xC, oy + 9, ...STEEL);
    line(png, xC + 1, oy - 3, xC + 1, oy + 8, ...STEEL_DARK);
  }
}

const sheet = newSheet(SHEET_W, SHEET_H);
const cell = (col, row) => [col * FRAME, row * FRAME];
for (let i = 0; i < 5; i++) drawSword(sheet, ...cell(i, 0), 'right', i - 2);   // atk_right
for (let i = 0; i < 4; i++) drawSword(sheet, ...cell(i, 1), 'right', i % 2 ? -1 : 0); // walk_right
for (let i = 0; i < 2; i++) drawSword(sheet, ...cell(i, 2), 'right', i ? 1 : 0);      // idle_right
for (let i = 0; i < 5; i++) drawSword(sheet, ...cell(i, 3), 'up', i - 2);
for (let i = 0; i < 4; i++) drawSword(sheet, ...cell(i, 4), 'up', i % 2 ? -1 : 0);
for (let i = 0; i < 2; i++) drawSword(sheet, ...cell(i, 5), 'up', i ? 1 : 0);
for (let i = 0; i < 5; i++) drawSword(sheet, ...cell(i, 6), 'down', i - 2);
for (let i = 0; i < 4; i++) drawSword(sheet, ...cell(i, 7), 'down', i % 2 ? -1 : 0);
for (let i = 0; i < 2; i++) drawSword(sheet, ...cell(i, 8), 'down', i ? 1 : 0);
await writeBoth('sword.png', sheet);
console.log(`  sword.png: 14x14 -> ${SHEET_W}x${SHEET_H} (5x9 of ${FRAME}x${FRAME})`);

const itemSheet = newSheet(192, 32);
for (let i = 0; i < 6; i++) drawSword(itemSheet, i * 32, 0, 'right', (i % 3) - 1);
await writeBoth('item-sword.png', itemSheet);
console.log(`  item-sword.png: NEW -> 192x32 (6x1 of 32x32)`);

const swordMeta = {
  id: 'sword', width: FRAME, height: FRAME,
  animations: {
    atk_right:  { length: 5, row: 0 }, walk_right: { length: 4, row: 1 }, idle_right: { length: 2, row: 2 },
    atk_up:     { length: 5, row: 3 }, walk_up:    { length: 4, row: 4 }, idle_up:    { length: 2, row: 5 },
    atk_down:   { length: 5, row: 6 }, walk_down:  { length: 4, row: 7 }, idle_down:  { length: 2, row: 8 },
  },
  offset_x: -8, offset_y: -12,
};
const itemSwordMeta = {
  id: 'item-sword', width: 32, height: 32,
  animations: { idle: { length: 6, row: 0 } }, offset_x: 0, offset_y: 0,
};
for (const dir of [SRC_SPR, PUB_SPR]) {
  await fs.writeFile(`${dir}/sword.json`, JSON.stringify(swordMeta, null, 2));
  await fs.writeFile(`${dir}/item-sword.json`, JSON.stringify(itemSwordMeta, null, 2));
}
console.log('  sword.json + item-sword.json written to shared + public');

console.log('\nDone.');
console.log(`Review folder: ${REVIEW}`);
